=== IARU-R1-C5/bandplan/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "f_start_hz": {
        "type": "number"
      },
      "f_stop_hz": {
        "type": "number"
      },
      "itu": {
        "type": "string"
      },
      "adif": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "sub_band": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "f_start_hz": {
              "type": "number"
            },
            "f_stop_hz": {
              "type": "number"
            },
            "name": {
              "type": "string"
            },
            "max_bw_hz": {
              "type": "number"
            },
            "use_repeaters": {
              "type": "boolean"
            },
            "use_satellites": {
              "type": "boolean"
            },
            "use_beacons": {
              "type": "boolean"
            },
            "mode_cw": {
              "type": "boolean"
            },
            "mode_dv": {
              "type": "boolean"
            },
            "mode_am": {
              "type": "boolean"
            },
            "mode_fm": {
              "type": "boolean"
            },
            "mode_ssb": {
              "type": "boolean"
            },
            "mode_mgm": {
              "type": "boolean"
            },
            "mode_all": {
              "type": "boolean"
            }
          },
          "required": [
            "f_start_hz",
            "f_stop_hz",
            "name",
            "max_bw_hz",
            "use_repeaters",
            "use_satellites",
            "use_beacons",
            "mode_cw",
            "mode_dv",
            "mode_am",
            "mode_fm",
            "mode_ssb",
            "mode_mgm",
            "mode_all"
          ]
        }
      }
    },
    "required": [
      "name",
      "f_start_hz",
      "f_stop_hz",
      "itu",
      "adif",
      "status",
      "sub_band"
    ]
  }
}

=== IARU-R1-C5/bandplan/bandplan.json
[
  {
    "name": "248 GHz",
    "f_start_hz": 241000000000,
    "f_stop_hz": 250000000000,
    "itu": "EHF",
    "adif": "1mm",
    "status": "Official",
    "sub_band": [
      {
        "f_start_hz": 248001000000,
        "f_stop_hz": 250000000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 248000000000,
        "f_stop_hz": 248001000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": true,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 241000000000,
        "f_stop_hz": 248000000000,
        "name": "not preferred fo usage",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      }
    ]
  },
  {
    "name": "144 GHz",
    "f_start_hz": 134000000000,
    "f_stop_hz": 141000000000,
    "itu": "EHF",
    "adif": "2mm",
    "status": "Official",
    "sub_band": [
      {
        "f_start_hz": 136000000000,
        "f_stop_hz": 141000000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": false
      },
      {
        "f_start_hz": 134930000000,
        "f_stop_hz": 136000000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 134928000000,
        "f_stop_hz": 134930000000,
        "name": "",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 134930000000,
        "f_stop_hz": 134930000000,
        "name": "Narrow band center of activity",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 134000000000,
        "f_stop_hz": 134928000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": true,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      }
    ]
  },
  {
    "name": "120 GHz",
    "f_start_hz": 122250000000,
    "f_stop_hz": 123000000000,
    "itu": "EHF",
    "adif": "2.5mm",
    "status": "Official",
    "sub_band": [
      {
        "f_start_hz": 122251000000,
        "f_stop_hz": 123000000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 122250000000,
        "f_stop_hz": 122251000000,
        "name": "Narrow band modes",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      }
    ]
  },
  {
    "name": "76 GHz",
    "f_start_hz": 75500000000,
    "f_stop_hz": 81500000000,
    "itu": "EHF",
    "adif": "4mm",
    "status": "Official",
    "sub_band": [
      {
        "f_start_hz": 78000000000,
        "f_stop_hz": 81500000000,
        "name": "not preferred fo usage",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 77501000000,
        "f_stop_hz": 78000000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 77500000000,
        "f_stop_hz": 77501000000,
        "name": "",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": true,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 77500200000,
        "f_stop_hz": 77500200000,
        "name": "Narrow band center of activity (not Preferred)",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 76000000000,
        "f_stop_hz": 77500000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 76032200000,
        "f_stop_hz": 76032200000,
        "name": "Narrow band center of activity (not Preferred)",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 75500000000,
        "f_stop_hz": 76000000000,
        "name": "",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": true,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 75976200000,
        "f_stop_hz": 75976200000,
        "name": "Narrow band center of activity",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      }
    ]
  },
  {
    "name": "47 GHz",
    "f_start_hz": 47000000000,
    "f_stop_hz": 47200000000,
    "itu": "EHF",
    "adif": "6mm",
    "status": "Official",
    "sub_band": [
      {
        "f_start_hz": 47090000000,
        "f_stop_hz": 47200000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": false
      },
      {
        "f_start_hz": 47088000000,
        "f_stop_hz": 47090000000,
        "name": "",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": true,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 47088200000,
        "f_stop_hz": 47088200000,
        "name": "Narrow band center of activity",
        "max_bw_hz": 2700,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
        "mode_dv": false,
        "mode_am": false,
        "mode_fm": false,
        "mode_ssb": false,
        "mode_mgm": false,
        "mode_all": true
      },
      {
        "f_start_hz": 47000000000,
        "f_stop_hz": 47088000000,
        "name": "",
        "max_bw_hz": 0,
        "use_repeaters": false,
        "use_satellites": false,
        "use_beacons": false,
        "mode_cw": false,
